#!/bin/bash

# Root of all my slackbuilds:
SBROOT=${SBROOT:-"/home/slackbuilds"}

# Package versions for wine and SDL_sound/OpenAL:
WINEREL=$(ls ${SBROOT}/wine/pkg64/current/wine-*.t?z |rev |cut -f3 -d- |rev)
FAUDIOREL=$(ls ${SBROOT}/FAudio/pkg/current/FAudio-*.t?z |rev |cut -f3 -d- |rev)
VKD3DREL=$(ls ${SBROOT}/vkd3d/pkg/current/vkd3d-*.t?z |rev |cut -f3 -d- |rev)

# Package locations for wine vkd3d and FAudio:
WINEPKG=$(ls ${SBROOT}/wine/pkg64/current/wine-*.t?z)
FAUDIOPKG=$(ls ${SBROOT}/FAudio/pkg/current/FAudio-*.t?z)
VKD3DPKG=$(ls ${SBROOT}/vkd3d/pkg/current/vkd3d-*.t?z)

# Convert the 32bit FAudio into a 'compat32' package:
convertpkg-compat32 -i ${FAUDIOPKG} -d /tmp

# Convert the 32bit vkd3d into a 'compat32' package:
convertpkg-compat32 -i ${VKD3DPKG} -d /tmp

# Create the SXZ module:
SCRATCHDIR=$(mktemp -t -d makesxz.XXXXXX)
installpkg --root $SCRATCHDIR ${WINEPKG}
installpkg --root $SCRATCHDIR /tmp/FAudio-compat32-${FAUDIOREL}-x86_64-*compat32.txz 
installpkg --root $SCRATCHDIR /tmp/vkd3d-compat32-${VKD3DREL}-x86_64-*compat32.txz 
./makemod $SCRATCHDIR ./optional/0060-wine-${WINEREL}-current-x86_64.sxz 
rm -r $SCRATCHDIR
